steps:
  - name: maven:3.6.0-jdk-11-slim
    entrypoint: 'mvn'
    args: ['package']
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-f', 'src/main/docker/Dockerfile.jvm', '-t', 'gcr.io/devops-tutorial-268713/devops-tutorial', '.' ]
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/devops-tutorial-268713/devops-tutorial']
images:
  - gcr.io/devops-tutorial-268713/devops-tutorial