version: "3"

services:
  webserver:
    image: registry.zouzland.com/boutry/devops-tutorial-native:0.3.0
    restart: always
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      quarkus.datasource.url: jdbc:postgresql://db:5432/user_api
      quarkus.hibernate-orm.database.generation: none
      quarkus.datasource.username: patrickfiori
      quarkus.datasource.password: NicePasswordM8
  db:
    image: postgres:latest
    restart: always
    expose:
      - "5432"
    environment:
      POSTGRES_PASSWORD: NicePasswordM8
      POSTGRES_USER: patrickfiori
      POSTGRES_DB: user_api
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./init_database.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres:
