quarkus:
  datasource:
    url: jdbc:mariadb://localhost:3306/APPLICATION
    driver: org.mariadb.jdbc.Driver
    username: ${database.username}
    password: ${database.password}
    min-size: 3
    max-size: 13
  hibernate-orm:
    database:
      generation: update # drop-and-create
    dialect: org.hibernate.dialect.MariaDB103Dialect
  resteasy:
    path: /api

"%test":
  quarkus:
    datasource:
      url: jdbc:tc:mysql:8.0.19://docker/APPLICATION
      driver: org.testcontainers.jdbc.ContainerDatabaseDriver
      username: ${database.username}
      password: ${database.password}
      min-size: 3
      max-size: 13
    hibernate-orm:
      database:
        generation: update # drop-and-create
      dialect: org.hibernate.dialect.MariaDB103Dialect
    resteasy:
      path: /api