quarkus:
  datasource:
    url: ${database.url}
    driver: ${database.driver}
    username: ${database.username}
    password: ${database.password}
    min-size: 3
    max-size: 13
  hibernate-orm:
    database:
      generation: update # drop-and-create
    dialect: org.hibernate.dialect.MariaDB103Dialect
  resteasy:
    path: /api