database:
  path: /tmp/data.csv



quarkus:
  datasource:
    url: jdbc:mariadb://localhost:3306/APPLICATION
    driver: org.mariadb.jdbc.Driver
    username: devops
    password: devops
    min-size: 3
    max-size: 13
  hibernate-orm:
    database:
      generation: drop-and-create