apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-k8s-persistence
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: /data/k8s/postgresql
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-k8s-persistence-claim
spec:
  storageClassName: slow
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
