apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-k8s-persistence
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: slow
  mountOptions:
    - hard
    - nfsvers=4.1
  local:
    path: /mnt/k8s
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - gl552vw
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-k8s-persistence-claim
spec:
  storageClassName: slow
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi