apiVersion: v1
kind: Service
metadata:
  name: k8s-webserver-service
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 30036
  selector:
    app: webserver
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: user-api-account
  labels:
    account: user-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver
  labels:
    app: webserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webserver
  template:
    metadata:
      labels:
        app: webserver
    spec:
      serviceAccountName: user-api-account
      containers:
        - name: webserver
          image: registry.zouzland.com/boutry/devops-tutorial-native:0.3.0
          ports:
            - containerPort: 8080
          env:
            - name: quarkus.datasource.url
              value: "jdbc:postgresql://postgres-service/APPLICATION"
            - name: quarkus.hibernate-orm.database.generation
              value: "drop-and-create"
      imagePullSecrets:
        - name: regcred
