apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: devops-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 31734 
      name: incoming-http
      protocol: HTTP
    hosts:
    - "*"
