version: "3"

services:
  webserver:
    image: registry.zouzland.com/boutry/devops-tutorial-native:0.3.0
    restart: always
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      quarkus.datasource.url: jdbc:postgresql://db:5432/APPLICATION
      quarkus.hibernate-orm.database.generation: none
  db:
    image: postgres:latest
    restart: always
    expose:
      - "5432"
    environment:
      POSTGRES_PASSWORD: devops
      POSTGRES_USER: devops
      POSTGRES_DB: APPLICATION
    volumes:
      - postgres-persistence:/var/lib/postgresql/data
      - ./init_database.sql:/docker-entrypoint-initdb.d/init.sql


volumes:
  postgres-persistence:
